project:
  type: website

website:
  title: "AAIC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: AAIC-Modules-Pyodide.qmd
        text: Pyodide
      - href: AAIC-Module-Thebe.qmd
        text: Thebe

format:
  html:
    theme: cosmo